"""Add price to store_products

Revision ID: 11c69a6bd077
Revises: 8fdce5b47d91
Create Date: 2025-03-06 13:47:54.484499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c69a6bd077'
down_revision = '8fdce5b47d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
