"""Dodanie pola customer_info

Revision ID: e34d0ed12170
Revises: 867e194a1205
Create Date: 2025-03-04 12:35:50.025220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34d0ed12170'
down_revision = '867e194a1205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('customer_info')

    # ### end Alembic commands ###
